### ISSUE TITLE
Example of YAML data file

### ISSUE THREAD

**Issue by ddnomad** [Neketek/CVBuilder#1]
Would be nice to have an example YAML data file under `/data` folder, otherwise it is rather time consuming to go over all template files to reconstruct a data file layout.

**Comment by Neketek** [comment]
I already addressed this issue.  Problem was in Readme. I just added a few more lines containing explicit instruction on how to find data example file for a particular template. In general, examples are located in a template folder, just because different templates may utilize different schemas.
